<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>auvdisk</AssemblyName>
    <Version>1.7.11</Version>
    <Authors>Alexander Automatl</Authors>
    <Company>Tomatl Inc</Company>
    <IsWindows Condition="$([MSBuild]::IsOSPlatform('Windows'))">true</IsWindows>
    <NoWarn>NETSDK1206</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="DiskAccessLibrary" Version="1.6.4.3" />
    <PackageReference Include="DotNext" Version="5.25.1" />
    <PackageReference Include="Lib.Harmony" Version="2.4.1" />
    <PackageReference Include="LTRData.DiscUtils" Version="1.0.66" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.228" Condition="'$(IsWindows)'=='true'">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Spectre.Console" Version="0.52.0" />
    <PackageReference Include="Win32.TokenPrivileges" Version="1.0.19073.2" Condition="'$(IsWindows)'=='true'">
        <NoWarn>NU1701</NoWarn>
    </PackageReference>
  </ItemGroup>
  <Target Name="PackChoco" DependsOnTargets="Publish">
     <Message Importance="High" Text="Packing $(PublishDir), generating nuspec:" />
     <Exec Command="python3 generate-choco-spec.py $(PublishDir)" />
     <Exec Command="choco pack auvdisk.choco.nuspec" />
  </Target>
  <PropertyGroup Condition="'$(IsWindows)'=='true'">
    <DefineConstants>WINDOWS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="auvdisk.test" />
  </ItemGroup>
</Project>
