<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>auvdisk</AssemblyName>
    <Version>1.5.0</Version>
    <Authors>Alexander Automatl</Authors>
    <Company>Tomatl Inc</Company>
    <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="DiskAccessLibrary" Version="1.6.4.3" />
    <PackageReference Include="DotNext" Version="5.25.1" />
    <PackageReference Include="LTRData.DiscUtils" Version="1.0.66" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.213">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Spectre.Console" Version="0.52.0" />
  </ItemGroup>
  <Target Name="PackChoco" DependsOnTargets="Publish">
     <Message Importance="High" Text="Packing $(PublishDir), generating nuspec:" />
     <Exec Command="python3 generate-choco-spec.py $(PublishDir)" />
     <Exec Command="choco pack auvdisk.choco.nuspec" />
  </Target>
  <PropertyGroup Condition="'$(IsWindows)'=='true'">
    <DefineConstants>WINDOWS</DefineConstants>
  </PropertyGroup>
</Project>
